#! /bin/sh

make aloha-upload
make bye_bye_1-upload
make bye_bye_2-upload
make candy_popcorn-upload
make gimme_gimme-upload
make give_give-upload
make heh_woo_snacks-upload
make here_we_go-upload
make hurry_hurry_take_my_picture-upload
make mahalo1-upload
make mahalo2-upload
make ohh_stitch_needs_popcorn-upload
make snacks1-upload
make snacks2-upload
make snacks3-upload
make stitch_made_himself_pretty-upload
make give_give_give_stitch_want_stitch_want-upload
make here_we_go_hee_hee-upload
make stitch_needs_snacks-upload
make wee_fun_fun_fun-upload
make wee_hee_hee_fun-upload
make wee_hee_hee_hee-upload
make weeee-upload
make wee_hee_hee_fun-upload
make woo_popcorn_yummy-upload
make yah_take_my_picture_yah-upload
make yay_woohoo_here_we_go_haha-upload
make yay_woohoo_here_we_go_hee_hee-upload
make big_hello-upload


make alan1-upload
make welcome_alan_bergman1-upload
make welcome_alan_bergman2-upload


make no_touch_stitch_1-upload
make no_touch_stitch_2-upload
make no_touch_stitch_3-upload

make stitch_giggle_1-upload
make stitch_giggle_2-upload
make stitch_giggle_3-upload
make stitch_giggle_4-upload
make stitch_giggle_5-upload
make stitch_giggle_6-upload

make stitch_ooo-upload

make meeta_nala_kweesta-upload
make echohahaha-upload

make growl1-upload
make growl2-upload
make hahahuh-upload
make hauu-upload
make heehah-upload
make hih_hahahah-upload
make hreh_huh_huh_weh-upload
make huh_weh-upload
make ooh-upload
make wahahah-upload
